apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-vpn
  namespace: media
  annotations:
    argocd.argoproj.io/tracking-id: qbittorrent-vpn:apps/Deployment:media/qbittorrent-vpn
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-vpn
  template:
    metadata:
      labels:
        app: qbittorrent-vpn
    spec:
      containers:
        - name: vpn
          image: dperson/openvpn-client:latest
          imagePullPolicy: Always
          command:
            - /sbin/tini
            - --
            - /usr/bin/openvpn.sh
            - -d
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: vpn-config
              mountPath: /vpn
            - name: dev-net-tun
              mountPath: /dev/net/tun

        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:version-5.1.4-r0
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Australia/Brisbane"
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - name: webui
              containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: qb-config
              mountPath: /config
            - name: qb-downloads
              mountPath: /downloads

      volumes:
        - name: vpn-config
          secret:
            secretName: qbittorrent-ovpn
            defaultMode: 420
            items:
              - key: vpn.conf
                path: vpn.conf

        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: ""

        - name: qb-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc

        - name: qb-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads-pvc
