apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"qbittorrent-vpn","namespace":"media"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"qbittorrent-vpn"}},"template":{"metadata":{"labels":{"app":"qbittorrent-vpn"}},"spec":{"containers":[{"command":["/sbin/tini","--","/usr/bin/openvpn.sh","-d"],"image":"dperson/openvpn-client:latest","name":"vpn","securityContext":{"capabilities":{"add":["NET_ADMIN"]},"privileged":true},"volumeMounts":[{"mountPath":"/vpn","name":"vpn-config"},{"mountPath":"/dev/net/tun","name":"dev-net-tun"}]},{"env":[{"name":"PUID","value":"1000"},{"name":"PGID","value":"1000"},{"name":"TZ","value":"Australia/Brisbane"},{"name":"WEBUI_PORT","value":"8080"}],"image":"lscr.io/linuxserver/qbittorrent:latest","name":"qbittorrent","ports":[{"containerPort":8080,"name":"webui"}],"volumeMounts":[{"mountPath":"/config","name":"qb-config"},{"mountPath":"/downloads","name":"qb-downloads"}]}],"volumes":[{"name":"vpn-config","secret":{"items":[{"key":"vpn.conf","path":"vpn.conf"}],"secretName":"qbittorrent-ovpn"}},{"hostPath":{"path":"/dev/net/tun"},"name":"dev-net-tun"},{"name":"qb-config","persistentVolumeClaim":{"claimName":"qbittorrent-config-pvc"}},{"name":"qb-downloads","persistentVolumeClaim":{"claimName":"qbittorrent-downloads-pvc"}}]}}}}
  name: qbittorrent-vpn
  namespace: media
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-vpn
  template:
    metadata:
      labels:
        app: qbittorrent-vpn
    spec:
      containers:
      - command:
        - /sbin/tini
        - --
        - /usr/bin/openvpn.sh
        - -d
        image: dperson/openvpn-client:latest
        imagePullPolicy: Always
        name: vpn
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /vpn
          name: vpn-config
        - mountPath: /dev/net/tun
          name: dev-net-tun
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Australia/Brisbane
        - name: WEBUI_PORT
          value: "8080"
        image: lscr.io/linuxserver/qbittorrent:latest
        imagePullPolicy: Always
        name: qbittorrent
        ports:
        - containerPort: 8080
          name: webui
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: qb-config
        - mountPath: /downloads
          name: qb-downloads
      volumes:
      - name: vpn-config
        secret:
          defaultMode: 420
          items:
          - key: vpn.conf
            path: vpn.conf
          secretName: qbittorrent-ovpn
      - hostPath:
          path: /dev/net/tun
          type: ""
        name: dev-net-tun
      - name: qb-config
        persistentVolumeClaim:
          claimName: qbittorrent-config-pvc
      - name: qb-downloads
        persistentVolumeClaim:
          claimName: qbittorrent-downloads-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-11-23T12:30:30Z"
    lastUpdateTime: "2025-11-23T12:46:55Z"
    message: ReplicaSet "qbittorrent-vpn-79bd649d49" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-11-24T10:34:58Z"
    lastUpdateTime: "2025-11-24T10:34:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
